### ISSUE TITLE
Restructure README

### ISSUE THREAD

**Issue by j-alicia-long** [thecourseforum/theCourseForum2#177] opened 2020-10-25 20:11 UTC
Current root directory readme is a giant wall of text. Consider adding screenshots of site pages to show state for current release version (launch upcoming), and also more helpful dev content (ex. debugging instructions, future plans, etc).

**Comment by Bartleby2718** [comment] 2021-03-14 02:59
This is a duplicate of #216. I'll close this since the other one has an assignee.

**Closed by Bartleby2718** 2021-03-14 02:59 UTC
Labels: Documentation
