### ISSUE TITLE
Grades UI Design

### ISSUE THREAD

**Issue by brian-yu** [thecourseforum/theCourseForum2#17] opened 2020-04-10 19:14 UTC
@sierraarnold this library might be the best way to display the grades data (via chart, pie chart, or whatever you think is best)

## Link to Chart Library
https://www.chartjs.org/

**Comment by bradknaysi** [comment] 2020-05-11 16:12
Is this referring to the instructor course page? This could be a duplicate of #14

**Closed** 2020-12-01 23:05 UTC
Labels: P0, UX/Design
